In [26]:
import pandas as pd
import numpy as np
import random
import string

### Data generation

In [27]:
##Actual input is a file, data generated for testing functions
num_names = 1000

names = [''.join(random.choices(string.ascii_letters, k=random.randint(5, 10))) for _ in range(num_names)]

df = pd.DataFrame({'Name': names})
yy=  [''.join(random.choices(['19','20','21','22'], k=1)) for _ in range(num_names)]
branch=  [''.join(random.choices(['BCB','BCE','BCT','BDS','BKT','BBS'], k=1)) for _ in range(num_names)]
regn=[]
for i in range(num_names):
    rand= random.randint(1, 4000)
    numb = str(rand).zfill(4)
    s=yy[i]+branch[i]+numb
    regn.append(s)
df['RegistrationNo']=regn
block=  [''.join(random.choices(['A','B','C','D','E','F','G','H'], k=1)) for _ in range(num_names)]
df['Block']=block
mess=  [''.join(random.choices(['Sakthi Veg','Sakthi Non-Veg', 'Darling-special', 'Neelkesh Veg', 'Neelkesh Special'], k=1)) for _ in range(num_names)]
df['MessType']=mess
for i in range(1,31):
    atten=  [''.join(random.choices(['P','A'], [0.8,0.2], k=1)) for _ in range(num_names)]
    date=str(i)
    df[date]=atten

In [28]:
df

,Name,RegistrationNo,Block,MessType,1,2,3,4,5,6,...,21,22,23,24,25,26,27,28,29,30
0,CjWCK,22BCE0075,F,Neelkesh Special,P,P,A,P,A,P,...,P,A,P,P,P,A,P,P,P,P
1,eftagd,20BCT2731,A,Sakthi Non-Veg,A,A,P,P,P,P,...,P,P,P,A,A,P,P,P,A,A
2,nQsNFT,20BDS0163,C,Neelkesh Special,P,P,P,P,P,P,...,P,P,P,P,P,A,P,P,P,A
3,EbTlDGX,21BCE2914,F,Sakthi Non-Veg,P,P,P,P,P,A,...,P,P,P,A,P,P,P,P,P,P
4,GCitcpYu,21BKT0310,B,Neelkesh Veg,P,A,P,A,P,P,...,P,P,P,P,P,P,P,P,A,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,UHCnNzUQ,21BCE2077,C,Sakthi Veg,P,P,P,P,P,P,...,P,P,P,P,P,P,P,P,A,P
996,NkSAPGa,19BKT1199,C,Darling-special,A,P,P,A,P,P,...,P,P,P,P,A,P,P,P,A,P
997,GTkmDFtUiR,21BCB0364,A,Sakthi Veg,P,P,P,P,P,P,...,P,A,P,A,P,P,P,P,P,P
998,rmverqNpxW,21BCT1549,D,Sakthi Veg,P,P,P,P,P,P,...,A,P,P,P,P,P,A,P,P,P
999,TrDMnV,21BBS2660,E,Darling-special,P,P,P,P,A,P,...,A,P,P,A,P,A,P,P,P,P

### Take file as input

### Data encoding and feature generation

In [29]:
def dataModification(df):
    mapping = {'A': 0, 'P': 1}
    for i in range(1,31):
        df[str(i)]=df[str(i)].map(mapping)
    dates=[]
    for i in range(1,31):
        dates.append(str(i))
    df['TotalPresent'] = df[dates].sum(axis=1)
    messWiseSortedDf = df.sort_values(by='MessType')
    return messWiseSortedDf

### No. of students enrolled in the mess

In [30]:
def messWiseStudentCount(df):
    grouped_df = df.groupby('MessType')
    group_count=grouped_df.size()
    return (group_count, grouped_df)

### Total meals in each mess

In [31]:
def totalMealCount(grouped_df):
    dict={}
    for group_name, group_data in grouped_df:
        print(f"Mess Caterer: {group_name}")
        print('Total meals')
        print(sum(group_data['TotalPresent']))
        print()
        dict[group_name]=sum(group_data['TotalPresent'])
    print(dict)

### Attendance report of each student mess wise

In [32]:
def generateAttendanceReport(grouped_df, mess_query):
    columns=['Name','RegistrationNo','Block','MessType']
    start_date=int(mess_query[0][0:2])
    end_date=int(mess_query[1][0:2])
    for i in range(start_date,end_date+1):
        columns.append(str(i))
    group_dfs = []
    group_names=[]
    for group_name, group_data in grouped_df:
        group_dfs.append(group_data)
        group_names.append(group_name)
        
    for i, group_df in enumerate(group_dfs):
        if group_names[i]==mess_query[2]:
            df=group_df[columns]
            print(group_names[i])
            print(df)

In [34]:
def main():
    #df=pd.read_csv('master.csv')
    mess_query=['01-03-2023','08-03-2023','Neelkesh Special']
    modifiedDf= dataModification(df)
    studetnsPerMessCount, messGroupedDf = messWiseStudentCount(modifiedDf)
    totalMeals = totalMealCount(messGroupedDf)
    generateAttendanceReport(messGroupedDf,mess_query)
    
if __name__ == "__main__":
    main()

Mess Caterer: Darling-special
Total meals
4635

{'Darling-special': 4635}
Mess Caterer: Neelkesh Special
Total meals
4967

{'Darling-special': 4635, 'Neelkesh Special': 4967}
Mess Caterer: Neelkesh Veg
Total meals
4714

{'Darling-special': 4635, 'Neelkesh Special': 4967, 'Neelkesh Veg': 4714}
Mess Caterer: Sakthi Non-Veg
Total meals
4680

{'Darling-special': 4635, 'Neelkesh Special': 4967, 'Neelkesh Veg': 4714, 'Sakthi Non-Veg': 4680}
Mess Caterer: Sakthi Veg
Total meals
4985

{'Darling-special': 4635, 'Neelkesh Special': 4967, 'Neelkesh Veg': 4714, 'Sakthi Non-Veg': 4680, 'Sakthi Veg': 4985}
Data required till which date: 3
1 8
Neelkesh Special
           Name RegistrationNo Block          MessType  1  2  3  4  5  6  7  8
476     fvvhmea      20BDS3319     D  Neelkesh Special  1  0  1  1  0  1  1  0
492      pCROPk      21BCB1729     F  Neelkesh Special  1  1  0  0  1  1  1  1
477  HmJFUGnVvi      20BCE2011     B  Neelkesh Special  1  1  1  1  1  1  0  1
491       uSYyZ      19BBS2837     E  Neelkesh Special  1  1  1  1  1  1  1  1
944   NwLbrZMre      21BKT0500     D  Neelkesh Special  1  1  1  1  0  1  1  1
..          ...            ...   ...               ... .. .. .. .. .. .. .. ..
48   RMsUPsGFyq      19BCT1375     E  Neelkesh Special  1  1  1  1  1  1  1  1
8    wWmFNsAvJf      20BCB1898     E  Neelkesh Special  1  1  0  0  0  1  1  0
36      AUHySeI      20BCB1252     B  Neelkesh Special  1  0  1  1  1  0  1  0
56    pvhuIGFMp      22BDS2415     D  Neelkesh Special  1  1  1  1  1  0  1  0
66       FGLSPU      21BBS1676     C  Neelkesh Special  1  1  1  1  1  1  1  1

[206 rows x 12 columns]